- name: Demo on Variables
  hosts: localhost
  vars_files:
    - sample-vars.yml
  vars:
    URL: google.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: "URL = {{ URL }}" #same line we are accessing variable with prefix $, here variable will be under {{ }}

- name: Variable type demo
  hosts: localhost
  vars:
    CLASS: devops
    timings:
      - 6am
      - 7am
    trainers:
      6am: john
      7am: bob
  tasks:
    - name: print
      ansible.builtin.debug:
        msg: "{{ CLASS }} - {{ timings[0]}} and the trainers are {{ trainers[6am]}}"


- name: Variable data types
  hosts: localhost
  vars:
    num1: 5
    num: 2.5
    str1: abc
    str2: abc123
    boolean1: yes
    boolean2: no
    boolean3: true
    boolean4: false
  tasks:
    - name: Print
      ansible.builtin.debug:
        msg: "i am the num containing {{ num1 }}"