- name: Demo on Variables
  hosts: all
  vars:
    URL: google.com
  tasks:
      - name: Print URL
        ansible.builtin.debug:
          msg: "URL" = {{ URL }} #same line we are accessing variable with prefix $, here variable will be under {{ }}
