- name: Facts
  hosts: localhost
  tasks:
    - name: Print Fact
      ansible.builtin.debug:
       var: ansible_date_time
#        var: ansible_default_ipv4
#        var: ansible_lo

      #       error  {{ ansible_lo.ipv4.netmask }}
        #        "{{ ansible_lo['ipv4']['netmask']}}"
        #"{{ ansible_is_chroot }}"
        #"{{ ansible_interfaces[0] }}"
