- name: Facts
  hosts: localhost
  tasks:
    - name: Print Fact
      ansible.builtin.debug:
        msg: "{{ ansible_lo['ipv4']['netmask']}}"
        #"{{ ansible_is_chroot }}"
        #"{{ ansible_interfaces[0] }}"
